# Generated by Django 6.0.4 on 2026-05-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_rsvp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='purpose',
            field=models.CharField(choices=[('cantar', 'Cantar'), ('bailar', 'Bailar')], default='cantar', max_length=10, verbose_name='¿Para qué?'),
        ),
    ]
